- name: Install pip3
  package:
    name: {{ alerta_server_dependencies }}
    state: present

- name: Create alerta server directory
  file:
    path: "{{ alerta_server_path }}"
    state: directory

- name: Install alerta server
  pip:
    name: "alerta-server=={{ alerta_server_version }}"
    executable: pip3
    state: latest

- name: Install alerta external plugins
  pip:
    name: "{{ alerta_server_external_plugins }}"
    executable: pip3
  when: alerta_server_external_plugins is defined and alerta_server_external_plugins|length>0

- name: create alerta system user
  user:
    name: alerta
    system: true
    shell: /usr/sbin/nologin
    createhome: false

- name: Copy uwsgi script
  copy:
    src: alertad-uwsgi.py
    dest: "{{ alerta_server_path }}"
    owner: "{{ alerta_server_user }}"
    group: "{{ alerta_server_user }}"
    mode: 0644

- name: configure alerta uwsgi
  template:
    src: alertad-uwsgi.ini.j2
    dest: /etc/alertad-uwsgi.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertad

- name: create systemd service unit
  template:
    src: alertad.service.j2
    dest: /etc/systemd/system/alertad.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertad

- name: configure alerta
  template:
    src: alertad.conf.j2
    dest: /etc/alertad.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertad

- name: "Check alerta-webui version"
  slurp:
    src: /etc/alerta-webui.version
  ignore_errors: yes
  register: alerta_webui_version_check

- include_tasks: alerta-webui.yml
  when: alerta_webui_version_check.content|default(None)|b64decode != alerta_webui_version
